hq/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from hq.views import (
    BlankSlotCreate, BlankSlotDelete, BlankSlotImportCsv, BlankSlotList,
    BlankSlotUpdate, BlankSlotValueList, BlankSlotValueUpdate,
    EmailDistributionCreate, Home, HqProfileUpdate, LinkDistributionCreate,
    LinkDistributionDelete, LinkDistributionDetail, LinkDistributionGenerate,
    LinkDistributionList, ManagerCreate, ManagerDelete, ManagerList,
    ManagerUpdate, MessageDistributionDelete, MessageDistributionDetail,
    MessageDistributionFallbackCreate, MessageDistributionHistory,
    MessageDistributionList, MessageDistributionSend,
    MessageDistributionUpdate, MessageList, PanelCreate, PanelDetail,
    PanelList, PanelManagerAssign, PanelManagerUnassign, PanelmemberList,
    PanelUpdate, ProfileExportCSV, SMSDistributionCreate, SurveyList,
    download_sms_stats,
)
from utils.views import blank_slot_export_csv

app_name = 'hq'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('profile/', HqProfileUpdate.as_view(), name='profile-update'),
    path('panelmembers/', PanelmemberList.as_view(), name='panelmember-list'),
    # SURVEYS
    path('surveys/', SurveyList.as_view(), name='survey-list'),
    # PANELS
    path('panels/', PanelList.as_view(), name='panel-list'),
    path('panels/create/', PanelCreate.as_view(), name='panel-create'),
    path('panels/<int:pk>/', PanelDetail.as_view(), name='panel-detail'),
    path('panels/<int:pk>/update/', PanelUpdate.as_view(), name='panel-update'),
    path('panels/<int:pk>/assign/', PanelManagerAssign.as_view(), name='panel-assign'),
    path('panels/<int:pk>/unassign/', PanelManagerUnassign.as_view(), name='panel-unassign'),
    # BLANK SLOTS
    path('blankslot/', BlankSlotList.as_view(), name='blankslot-list'),
    path('blankslot/create', BlankSlotCreate.as_view(), name='blankslot-create'),
    path('blankslot/<int:pk>/update/', BlankSlotUpdate.as_view(), name='blankslot-update'),
    path('blankslot/<int:pk>/delete', BlankSlotDelete.as_view(), name='blankslot-delete'),
    path('panelmembers/<int:pk>/blankslotvalues/', BlankSlotValueList.as_view(), name='blankslotvalue-list'),
    path('panelmembers/<int:pk>/blankslotvalues/update', BlankSlotValueUpdate.as_view(), name='blankslotvalue-update'),
    # MANAGERS
    path('managers/', ManagerList.as_view(), name='manager-list'),
    path('managers/create/', ManagerCreate.as_view(), name='manager-create'),
    path('managers/<int:pk>/update/', ManagerUpdate.as_view(), name='manager-update'),
    path('managers/<int:pk>/delete/', ManagerDelete.as_view(), name='manager-delete'),
    # MESSAGES
    path('messages/', MessageList.as_view(), name='message-list'),
    # EXPORT
    path('panelist/export/', ProfileExportCSV.as_view(), name='panelist-export'),
    path('blankslot/import/', BlankSlotImportCsv.as_view(), name='blank-slot-import'),
    path('blankslot/export/', blank_slot_export_csv, name='blank-slot-export'),
    # LINK DISTRIBUTIONS
    path('links/', LinkDistributionList.as_view(), name='link-distribution-list'),
    path('links/create/', LinkDistributionCreate.as_view(), name='link-distribution-create'),
    path('links/<int:pk>/', LinkDistributionDetail.as_view(), name='link-distribution-detail'),
    path('links/<int:pk>/delete/', LinkDistributionDelete.as_view(), name='link-distribution-delete'),
    path('links/<int:pk>/generate/', LinkDistributionGenerate.as_view(), name="link-distribution-generate"),
    # MESSAGE DISTRIBUTIONS
    path('msgdist/', MessageDistributionList.as_view(), name='msg-distribution-list'),
    path('msgdist/<int:pk>/', MessageDistributionDetail.as_view(), name='msg-distribution-detail'),
    path('msgdist/<int:pk>/smsstatscsv/', download_sms_stats, name='msg-distribution-dlsmsstats'),
    path('msgdist/create/email/', EmailDistributionCreate.as_view(), name='email-distribution-create'),
    path('msgdist/<int:pk>/delete/', MessageDistributionDelete.as_view(), name='msg-distribution-delete'),
    path('msgdist/create/sms/', SMSDistributionCreate.as_view(), name='sms-distribution-create'),
    path('msgdist/<int:pk>/send/', MessageDistributionSend.as_view(), name='msg-distribution-send'),
    path('msgdist/<int:pk>/panels/<int:panel_pk>/history/',
         MessageDistributionHistory.as_view(), name='msg-distribution-history'),
    path("msgdist/<int:pk>/fallback/", MessageDistributionFallbackCreate.as_view(),
         name='msg-distribution-fallback-create'),
    path('msgdist/<int:pk>/update/', MessageDistributionUpdate.as_view(), name='msg-distribution-update'),

]

manager/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from utils.views import blank_slot_export_csv

# -- QXSMS (LOCAL)
from .views import (
    BlankSlotValueImportCsv, BlankSlotValueList, BlankSlotValueUpdate, Home,
    LinkDistributionExport, ManagerProfileUpdate, MemberList,
    MessageDistributionDetail, MessageDistributionList, PanelDetail, PanelList,
    PanelSurveyDetail, PanelSurveyList, PanelUpdate, ProfileCreate,
    ProfileDeactivate, ProfileDelete, ProfileExportCsv, ProfileExportCustomCsv,
    ProfileImportCsv, ProfilePasswordReset, ProfileUpdate, TaskImportDetail,
    TaskImportList, download_sms_stats, members_import_csv_sample,
)

app_name = 'manager'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('profile/', ManagerProfileUpdate.as_view(), name='profile-update'),
    # PANELS
    path('panels/', PanelList.as_view(), name='panel-list'),
    path('panels/<int:pk>/', PanelDetail.as_view(), name='panel-detail'),
    path('panels/<int:pk>/update/', PanelUpdate.as_view(), name='panel-update'),
    path('panels/<int:pk>/members/', MemberList.as_view(), name='panel-member-list'),
    path('panels/<int:pk>/members/create/', ProfileCreate.as_view(), name='panel-member-create'),
    path('panels/<int:pk>/members/import/', ProfileImportCsv.as_view(), name='panel-member-import'),
    path('panels/<int:pk>/members/export/', ProfileExportCsv.as_view(), name='panel-member-export'),
    path('panels/<int:panel_pk>/members/export/blankslot/', blank_slot_export_csv, name='panel-blank-slot-export'),
    path('panels/<int:pk>/members/import/blankslot/', BlankSlotValueImportCsv.as_view(),
         name='panel-blank-slot-import'),
    path('panels/<int:pk>/members/export/custom', ProfileExportCustomCsv.as_view(),
         name='panel-member-export-custom'),
    path('panels/<int:pk>/surveys/', PanelSurveyList.as_view(), name='panel-survey-list'),
    path('panels/<int:pk>/surveys/<int:linkdistribution_pk>/export', LinkDistributionExport.as_view(),
         name='panel-survey-links-export'),
    path('panels/<int:pk>/surveys/<int:linkdistribution_pk>/', PanelSurveyDetail.as_view(),
         name='panel-survey-detail'),
    # BLANK SLOTS VALUES
    path('members/<int:pk>/blankslotvalues/', BlankSlotValueList.as_view(), name='blankslotvalue-list'),
    path('members/<int:pk>/blankslotvalues/update/', BlankSlotValueUpdate.as_view(),
         name='blankslotvalue-update'),
    # MEMBERS
    path('members/<int:pk>/update/', ProfileUpdate.as_view(), name='panel-member-update'),
    path('members/<int:pk>/delete/', ProfileDelete.as_view(), name='panel-member-delete'),
    path('members/<int:pk>/disable/', ProfileDeactivate.as_view(), name='panel-member-deactivate'),
    path('members/<int:pk>/password-change/reset/', ProfilePasswordReset.as_view(),
         name='panel-member-password-reset'),
    # SAMPLES
    path('samples/members/import/', members_import_csv_sample, name='members-import-sample'),
    # TASKS
    path('panels/<int:pk>/import/list/', TaskImportList.as_view(), name='task-import-list'),
    path('panels/<int:pk>/import/detail/<int:task_pk>/', TaskImportDetail.as_view(), name='task-import-detail'),
    # API
    # MESSAGE DISTRIBUTIONS
    path('panels/<int:pk>/msgdist/', MessageDistributionList.as_view(), name='msg-distribution-list'),
    path('panels/<int:pk>/msgdist/<int:msgdist_pk>/', MessageDistributionDetail.as_view(),
         name='msg-distribution-detail'),
    path('panels/<int:panel_pk>/msgdist/<int:msgdist_pk>/smsstatscsv/', download_sms_stats,
         name='msg-distribution-dlsmsstats'),
]

qxsms/urls.py
# -- DJANGO
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

# -- QXSMS
from panelist.views import EmailChangeConfirm, PhoneChangeConfirm
from qxauth.views import (
    GroupLogin, PasswordChange, PasswordReset, PasswordResetConfirm,
)
from qxsms import settings

app_name = 'qxsms'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GroupLogin.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password-change'),
    path('password-change/reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-change/reset/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(),
         name='password-reset-confirm'),
    path('email-change/<str:uidb64>/<str:token>/', EmailChangeConfirm.as_view(),
         name='email-change-confirm'),
    path('phone-change/<str:uidb64>/<str:token>/', PhoneChangeConfirm.as_view(),
         name='phone-change-confirm'),
    path('p/', include('panelist.urls')),
    path('m/', include('manager.urls')),
    path('hq/', include('hq.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('utils/', include('utils.urls')),
]

if settings.DEBUG:
    import debug_toolbar  # isort:skip

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('hijack/', include('hijack.urls', namespace='hijack')),
        path('dist/', include('distributions.urls'))
    ]

manager/models.py
# -- DJANGO
from django.db import models

# -- QXSMS
from hq.models import Panel


class GroupTaskImport(models.Model):
    celery_group_id = models.CharField(max_length=100)
    file_name = models.CharField(max_length=100)
    dry_run = models.BooleanField()
    upload_date = models.DateTimeField(auto_now_add=True)
    panel = models.ForeignKey(Panel, on_delete=models.CASCADE, null=True)
    success = models.BooleanField(default=False)

qxauth/models.py
# -- DJANGO
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import Group
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.db import models
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.encoding import force_bytes
from django.utils.html import strip_tags
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _

# -- THIRDPARTY
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber


class QxsmsUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        user = self.model(**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(password, **extra_fields)

    def create_superuser(self, password, **extra_fields):
        """
        Create and save an admin user with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(password, phone=None, **extra_fields)

    def get_by_natural_key(self, email_or_phone):
        key = 'phone' if isinstance(email_or_phone, PhoneNumber) else 'email'
        return self.get(**{key: email_or_phone})


class EverybodyIsFreeMixin:
    """Dummy methods so that the admin app works."""
    """https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#custom-users-and-django-contrib-admin"""

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True


class User(AbstractBaseUser, EverybodyIsFreeMixin):
    first_name = models.CharField(_('first name'), max_length=256, blank=True)
    last_name = models.CharField(_('last name'), max_length=256, blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    email = models.EmailField(
        _('email address'),
        blank=True,
        unique=True,
        null=True,
        error_messages={
            'unique': _("A user with that email address already exists."),
        }
    )
    phone = PhoneNumberField(
        _('phone number'),
        blank=True,
        null=True,
        unique=True,
        error_messages={
            'unique': _("A user with that phone number already exists."),
        }
    )

    # This might be subject to change,
    # https://gitlab.sciences-po.fr/cdspit/qxsms/issues/51
    is_superuser = models.BooleanField(
        _('superuser status'),
        default=False,
        help_text=_(
            'Designates that this user has all permissions without '
            'explicitly assigning them.'
        ),
    )

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        help_text=_(
            'The groups this user belongs to. A user will get all permissions '
            'granted to each of their groups.'
        ),
        related_name="user_set",
        related_query_name="user",
    )

    objects = QxsmsUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        swappable = 'AUTH_USER_MODEL'

    def save(self, *args, **kwargs):
        self.email = self.email or None
        self.phone = self.phone or None
        return super().save(*args, **kwargs)

    def clean(self):
        if not self.email and not self.phone:
            raise ValidationError('At least one of phone or email field must be set.')
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __str__(self):
        return self.get_username()

    def get_username(self):
        """Return the login username for this User."""
        return self.email or str(self.phone)

    def get_tokens(self):
        uid = urlsafe_base64_encode(force_bytes(self.pk))
        token = default_token_generator.make_token(self)
        return [uid, token]

    def create_password_reset_link(self, request):
        path = reverse('password-reset-confirm', args=self.get_tokens())
        return request.build_absolute_uri(path)

    def send_welcome(self, request=None, template_name='qxauth/welcome_nc.html', subject="Message from WPSS"):
        link = self.create_password_reset_link(request)

        context = {
            'first_name': self.first_name,
            'last_name': self.last_name,
            'link': link,
        }
        html_message = render_to_string(template_name, context)
        send_mail(
            subject=subject,
            message=strip_tags(html_message),
            from_email=settings.DEFAULT_FROM_EMAIL,
            recipient_list=[self.email],
            html_message=html_message,
        )

manager/templates/manager/panel_member_list.html
{% extends 'manager/panel_detail.html' %}
{% load qxsms_tags i18n django_bootstrap5 %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'manager:panel-member-list' panel.pk %}{% trans "Panelists" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans "Panelist accounts belonging to this panel" %}{% endblock %}
{% block content %}
    <section class="container-fluid mw-1920">
        <div class="btn-toolbar mb-3">
            <div class="btn-group">
                <a href="{% url 'manager:panel-member-create' panel.pk %}" class="btn btn-success">{% icon 'plus-lg' 'me-2' %}{% trans "New panelist" %}</a>
                <div class="btn-group">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="import-menu-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        {% icon 'upload' 'me-2' %}{% trans "Import" %}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="import-menu-dropdown">
                        <a class="dropdown-item" href="{% url 'manager:panel-member-import' panel.pk %}">{% trans "Panelists" %}</a>
                        <a class="dropdown-item" href="{% url 'manager:panel-blank-slot-import' panel.pk %}">{% trans "Additional variables" %}</a>
                    </div>
                </div>
                <div class="btn-group">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="export-menu-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        {% icon 'download' 'me-2' %}{% trans "Export" %}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="export-menu-dropdown">
                        <h6 class="dropdown-header">{% trans "Panelists" %}</h6>
                        <a class="dropdown-item" href="{% url 'manager:panel-member-export' panel.pk %}">{% trans "With default fields" %}</a>
                        <a class="dropdown-item" href="{% url 'manager:panel-member-export-custom' panel.pk %}">{% trans "With custom fields" %}</a>
                        <a class="dropdown-item" href="{% url 'manager:panel-member-export' panel.pk %}?all">{% trans "With all fields" %}</a>
                        <hr class="dropdown-divider">
                        <a class="dropdown-item" href="{% url 'manager:panel-blank-slot-export' panel.pk %}">{% trans "Additional variables" %}</a>
                    </div>
                </div>
            </div>
        </div>
        <p>
            Summary of language codes: {% for lang in language_codes %}'{{ lang }}'{% if not forloop.last %} {% endif %}{% endfor %}
        </p>
        {% include 'utils/table_filter.html' with form=filter.form counts=counts %}
        {% if object_list %}
            <div class="table-responsive">
                <table class="table table-bordered table-hover bg-white">
                    <thead class="table-light">
                        <tr>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    ID{% include 'utils/table_header_column_sort.html' with order_by='ess_id' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    First name{% include 'utils/table_header_column_sort.html' with order_by='first_name' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Last name{% include 'utils/table_header_column_sort.html' with order_by='last_name' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Sex{% include 'utils/table_header_column_sort.html' with order_by='sex' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Email{% include 'utils/table_header_column_sort.html' with order_by='email' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Phone{% include 'utils/table_header_column_sort.html' with order_by='phone' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Language{% include 'utils/table_header_column_sort.html' with order_by='language' %}
                                </div>
                            </th>
                            <th>State</th>
                            <th>Additional variables</th>
                            <th>Edit</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for panelist in object_list %}
                        <tr>
                            <td>{{ panelist.panelist_id }}</td>
                            <td>{{ panelist.first_name }}</td>
                            <td>{{ panelist.last_name }}</td>
                            <td>{{ panelist.get_sex_display }}</td>
                            <td>{{ panelist.email }}</td>
                            <td>{{ panelist.phone }}</td>
                            <td><span class="badge rounded-pill bg-secondary">{{ panelist.language|upper }}</span></td>
                            <td><span class="badge rounded-pill {{ panelist.state_label.1 }}">{{ panelist.state_label.0 }}</span></td>
                            <td>
                                <a class="btn btn-sm btn-info" href="{% url 'manager:blankslotvalue-list' panelist.pk %}">
                                    {% icon 'search' %}
                                </a>
                            </td>
                            <td>
                                <a class="btn btn-sm btn-info" href="{% url 'manager:panel-member-update' panelist.pk %}">
                                    {% icon 'pen' %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% bootstrap_pagination page=page_obj url=request.get_full_path %}
        {% else %}
            <div class="alert alert-info">{% trans "No panelist" %}</div>
        {% endif %}
    </section>
{% endblock %}

manager/templates/manager/panel_member_update.html
{% extends 'manager/base.html' %}
{% load qxsms_tags i18n django_bootstrap5 %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'manager:panel-list' %}{% trans "Panels" %}{% endbreadcrumbitem %}
    {% breadcrumbitem 'manager:panel-member-list' profile.panel.pk %}{{ profile.panel.name }}{% endbreadcrumbitem %}
    {% breadcrumbitem 'manager:panel-member-list' profile.panel.pk %}{% trans "Panelists" %}{% endbreadcrumbitem %}
    {% breadcrumbitem 'manager:panel-member-update' profile.pk %}{% trans "Update panelist information" %}{% endbreadcrumbitem %}
{% endblock %}

{% block content %}
    <section class="container">
        {% if object.anonymized_since %}
            <div class="alert alert-warning">This panelist has been deactivated since {{ object.anonymized_since }}. Contact information has been anonymized.</div>
        {% endif %}
        <form method="post">
            <div class="mb-3">
                <label for="id_panelist_id" class="form-label">{% trans "Panelist ID" %}</label>
                <input id="id_panelist_id" class="form-control" type="text" value="{{ profile.panelist_id }}" disabled/>
            </div>
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="float-md-start">
                <button type="submit" class="btn btn-success me-2">{% trans "Save" %}</button>
                {% url 'manager:panel-member-list' profile.panel_id as cancel_url %}
                {% include 'utils/cancel_button.html' %}
            </div>
        </form>
        <div class="float-md-end d-flex flex-wrap mt-3 mt-md-0">
            {% if object.is_active %}
                <div class="btn-group me-2">
                    <button class="btn btn-warning dropdown-toggle" type="button" id="pwd-menu-dropdown" data-bs-toggle="dropdown" aria-expanded="false">{% trans "Send password change link" %}</button>
                    <div class="dropdown-menu" aria-labelledby="pwd-menu-dropdown">
                        <form method="post" action="{% url 'manager:panel-member-password-reset' object.pk %}?phone">
                            {% csrf_token %}
                            <input type="hidden" name="email_0" id="id_email_0" value="+{{ profile.phone.country_code }}">
                            <input type="hidden" name="email_1" id="id_email_1" value="{{ profile.phone.national_number }}">
                            <button class="dropdown-item"{% if not profile.phone %} title="No associated phone number." disabled{% endif %}>{% trans 'By phone' %}</button>
                        </form>
                        <form method="post" action="{% url 'manager:panel-member-password-reset' object.pk %}">
                            {% csrf_token %}
                            <input type="hidden" name="email" id="id_email" value="{{ profile.email }}">
                            <button class="dropdown-item"{% if not profile.email %} title="No associated email address." disabled{% endif %}>{% trans 'By email' %}</button>
                        </form>
                    </div>
                </div>
                <a href="{% url 'manager:panel-member-deactivate' object.pk %}" class="btn btn-warning me-2">{% trans "Anonymize & Deactivate" %}</a>
            {% endif %}
            <a href="{% url 'manager:panel-member-delete' object.pk %}" class="btn btn-danger">{% trans "Delete" %}</a>
        </div>
    </section>
{% endblock %}

manager/templates/manager/panel_survey_detail.html
{% extends 'manager/panel_survey_list.html' %}
{% load qxsms_tags i18n django_bootstrap5 %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'manager:panel-survey-detail' panel.pk object.pk %}{{ object }}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans "Detailed responses statuses" %}{% endblock %}
{% block content %}
    <section class="container">
        {% include 'utils/table_filter.html' with form=filter.form counts=counts %}
        {% if object_list %}
            {% include 'utils/distribution_stats.html' with records_stats=records_stats %}
            <div class="table-responsive">
                <table class="table table-bordered bg-white mb-3">
                    <thead class="table-light">
                    <tr>
                        <th>
                            <div class="d-flex justify-content-between align-items-end">
                                {% trans "ESS ID" %}{% include 'utils/table_header_column_sort.html' with order_by='ess_id' %}
                            </div>
                        </th>
                        <th>
                            <div class="d-flex justify-content-between align-items-end">
                                {% trans "Panelist" %}{% include 'utils/table_header_column_sort.html' with order_by='full_name' %}
                            </div>
                        </th>

                        <th>
                            <div class="d-flex justify-content-between align-items-end">
                                {% trans "Started at" %}{% include 'utils/table_header_column_sort.html' with order_by='started_at' %}
                            </div>
                        </th>
                        <th>
                            <div class="d-flex justify-content-between align-items-end">
                                {% trans "Finished at" %}
                            </div>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for l in profiles.object_list %}
                        <tr class="{% if l.finished %}bg-success {% elif l.started %}bg-warning{% elif l.partially_finished %}bg-danger opacity-75{% else %}bg-danger{% endif %} text-white bg-gradient">
                            <td><a class ="text-white" href="{% url 'manager:panel-member-update' l.profile_id %}">{{ l.ess_id }}</a></td>
                            <td>{{ l.full_name }}</td>
                            <td>{{ l.started_at|default:'' }}</td>
                            {% if l.finished and not l.completed_at %}
                                {# Date unknown because "anonymize responses" is enabled in the survey settings #}
                                <td>Unknown (anonymized)</td>
                            {% else %}
                                <td>{{ l.completed_at|default:'' }}</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {% bootstrap_pagination page=profiles url=request.get_full_path %}
            </div>
            <a class="btn btn-secondary mb-3" href="{% url 'manager:panel-survey-links-export' panel.pk object.pk %}">
            {% icon 'download' 'me-2' %}{% trans "Export response statuses" %}
            </a>
        {% else %}
            <div class="alert alert-info">
                {% if counts.total != counts.grand_total %}
                    {% trans "No result" %}
                {% else %}
                    {% trans "No links were generated for this distribution (maybe the panel was empty when the survey was distributed)" %}
                {% endif %}
            </div>
        {% endif %}
    </section>
{% endblock %}

manager/templates/manager/password_change.html
{% extends 'manager/base.html' %}
{% load qxsms_tags django_bootstrap5 i18n %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem %}{% trans "Password change" %}{% endbreadcrumbitem %}
{% endblock %}

{% block title_lead %}{{ user }}{% endblock %}

{% block content %}
    {% url 'manager:profile-update' as cancel_url %}
    {% include 'password_change_form.html' %}
{% endblock %}