hq/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from hq.views import (
    BlankSlotCreate, BlankSlotDelete, BlankSlotImportCsv, BlankSlotList,
    BlankSlotUpdate, BlankSlotValueList, BlankSlotValueUpdate,
    EmailDistributionCreate, Home, HqProfileUpdate, LinkDistributionCreate,
    LinkDistributionDelete, LinkDistributionDetail, LinkDistributionGenerate,
    LinkDistributionList, ManagerCreate, ManagerDelete, ManagerList,
    ManagerUpdate, MessageDistributionDelete, MessageDistributionDetail,
    MessageDistributionFallbackCreate, MessageDistributionHistory,
    MessageDistributionList, MessageDistributionSend,
    MessageDistributionUpdate, MessageList, PanelCreate, PanelDetail,
    PanelList, PanelManagerAssign, PanelManagerUnassign, PanelmemberList,
    PanelUpdate, ProfileExportCSV, SMSDistributionCreate, SurveyList,
    download_sms_stats,
)
from utils.views import blank_slot_export_csv

app_name = 'hq'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('profile/', HqProfileUpdate.as_view(), name='profile-update'),
    path('panelmembers/', PanelmemberList.as_view(), name='panelmember-list'),
    # SURVEYS
    path('surveys/', SurveyList.as_view(), name='survey-list'),
    # PANELS
    path('panels/', PanelList.as_view(), name='panel-list'),
    path('panels/create/', PanelCreate.as_view(), name='panel-create'),
    path('panels/<int:pk>/', PanelDetail.as_view(), name='panel-detail'),
    path('panels/<int:pk>/update/', PanelUpdate.as_view(), name='panel-update'),
    path('panels/<int:pk>/assign/', PanelManagerAssign.as_view(), name='panel-assign'),
    path('panels/<int:pk>/unassign/', PanelManagerUnassign.as_view(), name='panel-unassign'),
    # BLANK SLOTS
    path('blankslot/', BlankSlotList.as_view(), name='blankslot-list'),
    path('blankslot/create', BlankSlotCreate.as_view(), name='blankslot-create'),
    path('blankslot/<int:pk>/update/', BlankSlotUpdate.as_view(), name='blankslot-update'),
    path('blankslot/<int:pk>/delete', BlankSlotDelete.as_view(), name='blankslot-delete'),
    path('panelmembers/<int:pk>/blankslotvalues/', BlankSlotValueList.as_view(), name='blankslotvalue-list'),
    path('panelmembers/<int:pk>/blankslotvalues/update', BlankSlotValueUpdate.as_view(), name='blankslotvalue-update'),
    # MANAGERS
    path('managers/', ManagerList.as_view(), name='manager-list'),
    path('managers/create/', ManagerCreate.as_view(), name='manager-create'),
    path('managers/<int:pk>/update/', ManagerUpdate.as_view(), name='manager-update'),
    path('managers/<int:pk>/delete/', ManagerDelete.as_view(), name='manager-delete'),
    # MESSAGES
    path('messages/', MessageList.as_view(), name='message-list'),
    # EXPORT
    path('panelist/export/', ProfileExportCSV.as_view(), name='panelist-export'),
    path('blankslot/import/', BlankSlotImportCsv.as_view(), name='blank-slot-import'),
    path('blankslot/export/', blank_slot_export_csv, name='blank-slot-export'),
    # LINK DISTRIBUTIONS
    path('links/', LinkDistributionList.as_view(), name='link-distribution-list'),
    path('links/create/', LinkDistributionCreate.as_view(), name='link-distribution-create'),
    path('links/<int:pk>/', LinkDistributionDetail.as_view(), name='link-distribution-detail'),
    path('links/<int:pk>/delete/', LinkDistributionDelete.as_view(), name='link-distribution-delete'),
    path('links/<int:pk>/generate/', LinkDistributionGenerate.as_view(), name="link-distribution-generate"),
    # MESSAGE DISTRIBUTIONS
    path('msgdist/', MessageDistributionList.as_view(), name='msg-distribution-list'),
    path('msgdist/<int:pk>/', MessageDistributionDetail.as_view(), name='msg-distribution-detail'),
    path('msgdist/<int:pk>/smsstatscsv/', download_sms_stats, name='msg-distribution-dlsmsstats'),
    path('msgdist/create/email/', EmailDistributionCreate.as_view(), name='email-distribution-create'),
    path('msgdist/<int:pk>/delete/', MessageDistributionDelete.as_view(), name='msg-distribution-delete'),
    path('msgdist/create/sms/', SMSDistributionCreate.as_view(), name='sms-distribution-create'),
    path('msgdist/<int:pk>/send/', MessageDistributionSend.as_view(), name='msg-distribution-send'),
    path('msgdist/<int:pk>/panels/<int:panel_pk>/history/',
         MessageDistributionHistory.as_view(), name='msg-distribution-history'),
    path("msgdist/<int:pk>/fallback/", MessageDistributionFallbackCreate.as_view(),
         name='msg-distribution-fallback-create'),
    path('msgdist/<int:pk>/update/', MessageDistributionUpdate.as_view(), name='msg-distribution-update'),

]

qxsms/urls.py
# -- DJANGO
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

# -- QXSMS
from panelist.views import EmailChangeConfirm, PhoneChangeConfirm
from qxauth.views import (
    GroupLogin, PasswordChange, PasswordReset, PasswordResetConfirm,
)
from qxsms import settings

app_name = 'qxsms'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GroupLogin.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password-change'),
    path('password-change/reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-change/reset/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(),
         name='password-reset-confirm'),
    path('email-change/<str:uidb64>/<str:token>/', EmailChangeConfirm.as_view(),
         name='email-change-confirm'),
    path('phone-change/<str:uidb64>/<str:token>/', PhoneChangeConfirm.as_view(),
         name='phone-change-confirm'),
    path('p/', include('panelist.urls')),
    path('m/', include('manager.urls')),
    path('hq/', include('hq.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('utils/', include('utils.urls')),
]

if settings.DEBUG:
    import debug_toolbar  # isort:skip

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('hijack/', include('hijack.urls', namespace='hijack')),
        path('dist/', include('distributions.urls'))
    ]

distributions/models.py
# -- STDLIB
import logging
import uuid
from typing import Iterable, List, Set, Tuple

# -- DJANGO
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# -- QXSMS
from panelist.models import Profile


class Survey(models.Model):
    qx_id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Distribution(models.Model):

    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=200)
    qx_id = models.CharField(max_length=20, unique=True, null=True)
    qx_import_id = models.CharField(max_length=20, unique=True, null=True)
    qx_created_date = models.DateTimeField(null=True)

    class Meta:
        abstract = True
        ordering = ['-created_date']

    @property
    def short_uid(self):
        if self.uid is None:
            return ''
        return self.uid.hex[:8]

    def __str__(self):
        descr = self.description or ''
        return f"({self.short_uid}) {descr}"

    def candidates(self, *args, **kwargs):
        raise NotImplementedError

    def contacts_for_import(self):
        raise NotImplementedError

    def save_links(self):
        raise NotImplementedError

    def get_import_kwargs(self):
        """Keyword arguments as expected by `client.import_contacts()`"""
        return {'list_id': self.qx_list_id, 'contacts': self.contacts_for_import()}


def _update_links(links: Iterable['Link'], qx_links: List[dict]) -> Tuple[List['Link'], List['Link']]:
    """Set `Link` attributes using links fetched from Qualtrics

    The normal behavior is that each `Link` instance has exactly one counterpart in `qx_list`.
    If no corresponding Qualtrics link is found, log the error.
    Return updated and skipped instances separately to the caller.
    """
    by_ext_ref = {qxl['externalDataReference']: qxl for qxl in qx_links}
    updated = []
    skipped = []
    for link in links:
        ext_ref = link.profile_id.hex
        try:
            qx_link = by_ext_ref[ext_ref]
        except KeyError:
            logging.error("missing Qualtrics link for %s", link.profile_id)
            skipped.append(link)
            continue
        link.qx_contact_id = qx_link.get('contactId')
        link.url = qx_link.get('link')
        if not (link.qx_contact_id and link.url):
            logging.error("missing contactId or link in record: %s", qx_link)
            skipped.append(link)
            continue
        updated.append(link)
    return updated, skipped


class LinkDistribution(Distribution):

    qx_list_id = models.CharField(max_length=20, unique=True, null=True)
    expiration_date = models.DateTimeField(blank=False, null=True)
    survey = models.ForeignKey('Survey', to_field='qx_id', related_name="distributions",
                               limit_choices_to={'is_active': True}, on_delete=models.PROTECT)
    panels = models.ManyToManyField('hq.Panel', related_name="distributions")

    def get_absolute_url(self):
        return reverse('dist:detail', args=[self.pk])

    def candidates(self):
        return Profile.objects.filter(panel__in=self.panels.all(), is_opt_out=False)

    @property
    def count_candidates(self):
        return self.candidates().count()

    def contacts_for_import(self):
        """Serialize contacts that need a link, in the format expected by Qualtrics imports

        Intended to be called *after* `save_links()`. Another choice would have been to call
        `candidates()` to get the target queryset, but this would leave the possibility of the set
        of candidates having changed since we called `save_links()`...
        """
        profiles = Profile.objects.prefetch_related('blankslotvalue_set__blankslot').filter(link__distribution=self)
        return [p.to_json() for p in profiles]

    def save_links(self):
        """Create links with empty URLs to record the profiles for which link generation is intended

        By creating `Link` instances *before* creating the distribution on Qualtrics, we can confirm that
        all intended recipients indeed got a link generated.
        """
        profiles = self.candidates()
        links = [Link(profile=profile, distribution=self) for profile in profiles]
        self.links.all().delete()
        return Link.objects.bulk_create(links)

    def update_links(self, qx_links: List[dict]) -> Tuple[List['Link'], List['Link']]:
        """Update database links with data from their corresponding Qualtrics link

        `Link` instances for each recipient saved in the database before the Qualtrics distribution is created.
        Once the links are generated on Qualtrics and retrieved, we need to set `Link.qx_contact_id` and
        `Link.url` on their counterparts.

        The pairing between a Qualtrics link and a database `Link` is done using `externalDataReference`, which
        matches `Link.profile_id`.
        """
        updated, skipped = _update_links(self.links.all(), qx_links)
        Link.objects.bulk_update(updated, fields=['qx_contact_id', 'url'])
        return updated, skipped

    @property
    def is_expired(self):
        return timezone.now() > self.expiration_date


class Link(models.Model):
    # TODO Parse and cache URL components for use in __str__
    URL_PATTERN = r'^.*(?P<survey_qx_id>SV_.*)\?Q_CHL=gl&Q_DL=(?P<qx_id>.*)$'

    profile = models.ForeignKey('panelist.Profile', to_field='uid', related_name='links', related_query_name='link',
                                on_delete=models.CASCADE)
    distribution = models.ForeignKey('LinkDistribution', on_delete=models.CASCADE,
                                     related_name='links', related_query_name='link')
    url = models.URLField()
    qx_contact_id = models.CharField(max_length=20)

    class Meta:
        unique_together = ('profile', 'distribution')

    def __str__(self):
        dist_id = profile_id = ""
        if self.distribution_id is not None:
            dist_id = str(self.distribution_id)[:8]
        if self.profile_id is not None:
            profile_id = str(self.profile_id)[:8]
        return (f"dist={dist_id}, "
                f"profile={profile_id}")


# Message distributions (Email and SMS)
# -------------------------------------

class MessageDistribution(Distribution):

    MODE_EMAIL = 0
    MODE_SMS = 1
    CONTACT_MODE_CHOICES = (
        (MODE_EMAIL, _("Email")),
        (MODE_SMS, _("SMS")),
    )

    TARGET_ALL = 0
    TARGET_NOT_FINISHED = 1
    TARGET_FINISHED = 2
    TARGET_CHOICES = (
        (TARGET_ALL, _("All")),
        (TARGET_NOT_FINISHED, _("Not finished (proper target for reminders)")),
        (TARGET_FINISHED, _("Finished"))
    )

    link_distribution = models.ForeignKey('LinkDistribution', on_delete=models.CASCADE,
                                          related_name="%(class)ss", related_query_name="%(class)s",
                                          # TODO Really necessary restriction ?
                                          limit_choices_to={'qx_id__isnull': False})
    qx_batch_id = models.CharField(max_length=20, unique=True, null=True)
    contact_mode = models.PositiveSmallIntegerField(choices=CONTACT_MODE_CHOICES)
    target = models.PositiveSmallIntegerField(choices=TARGET_CHOICES, verbose_name=_("Target recipients"))
    send_date = models.DateTimeField(blank=False, null=True)
    links = models.ManyToManyField('Link', related_name="message_distributions",
                                   related_query_name='message_distribution')
    message = models.ForeignKey('Message', related_name="email_message_of_set",
                                related_query_name='email_message_of', on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey('Message', related_name="email_subject_of_set",
                                related_query_name='email_subject_of', on_delete=models.SET_NULL, null=True)
    fallback_of = models.OneToOneField('self', related_name='fallback', null=True, on_delete=models.CASCADE)

    @property
    def qx_list_id(self):
        list_id = None
        if self.link_distribution_id is not None:
            list_id = self.link_distribution.qx_list_id
        return list_id

    @property
    def is_email(self):
        return self.contact_mode == MessageDistribution.MODE_EMAIL

    @property
    def is_sms(self):
        return self.contact_mode == MessageDistribution.MODE_SMS

    @property
    def fallback_contact_mode(self):
        return MessageDistribution.MODE_EMAIL if self.is_sms else MessageDistribution.MODE_SMS

    @property
    def contact_label(self):
        return "Sms" if self.is_sms else "Email"

    @property
    def fallback_label(self):
        return "Sms" if self.is_email else "Email"

    @property
    def is_fallback(self):
        return self.fallback_of is not None

    @property
    def has_fallback(self):
        return hasattr(self, 'fallback')

    @property
    def can_add_fallback(self):
        return not (self.is_fallback or self.has_fallback)

    @property
    def has_history(self):
        """Whether a detailed history of response statuses is available

        Qualtrics does not seem to support response history for SMS distributions.
        """
        return self.qx_id and self.is_email

    def get_send_date(self):
        if self.fallback_of is not None:
            return self.fallback_of.send_date
        return self.send_date

    def get_absolute_url(self):
        return reverse('dist:msgd:detail', args=[self.pk])

    def contacts_for_import(self):
        return [_contact_from_link(link) for link in self.links.select_related('profile__panel')]

hq/models.py
# -- STDLIB
import logging

# -- DJANGO
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)
User = get_user_model()


class Panel(models.Model):
    managers = models.ManyToManyField(User, blank=True)
    name = models.CharField(max_length=256)
    incentive_amount = models.CharField(max_length=256, blank=True, help_text=_("Value and currency."))
    contact_info = models.TextField(
        null=True,
        blank=True,
        help_text=_("Content that will be displayed in the \"Contact us\" section "
                    "at the end of the panelist portal help page. "
                    "If not set, the manager contact information will be displayed by default.")
    )

    def __str__(self):
        return self.name


class SMSStats(models.Model):
    panelist = models.ForeignKey("panelist.Profile", on_delete=models.CASCADE)
    msgdist = models.ForeignKey("distributions.MessageDistribution", on_delete=models.CASCADE)
    smsstatus = models.CharField(max_length=255, null=True)
    bouncereason = models.CharField(max_length=255, null=True)
    datefile = models.DateTimeField(null=True)

    def __repr__(self):
        return f"{self.panelist}|{self.msgdist}|{self.datefile}"

hq/templates/hq/msgdist/detail.html
{% extends "hq/base.html" %}
{% load static qxsms_tags i18n %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'hq:msg-distribution-list' %}{% trans "Message deliveries" %}{% endbreadcrumbitem %}
    {% breadcrumbitem 'hq:msg-distribution-detail' object.pk %}{% trans "Message delivery details" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans "Detailed summary of this message delivery's settings" %}{% endblock %}
{% block content %}
    <section class="container">
        {% include 'hq/msgdist/msgdist_details.html' %}
        {% if object.qx_id %}
            {% if object.is_email %}
                <h1>Stats</h1>
                {% include 'hq/msgdist/email_stats_by_panel.html' %}
            {% else %}
                <h1>Stats preview for ALL panels in this distribution</h1>
                {% include 'utils/sms_stats.html' %}
                {% if detailedstatssms %}
                    <h1>Detailed stats</h1>
                   <table class="table table-bordered bg-white mb-3">
                        <thead class="table-light">
                        <th>Panelist ID</th>
                        <th>Status</th>
                        <th>Bounce Reason</th>
                        <th>Last status update</th>
                        </thead>
                        <tbody>
                            {% for stat in detailedstatssms %}
                                <tr>
                                    <td>{{ stat.panelist.panelist_id }}</td>
                                    <td>{{ stat.smsstatus }}</td>
                                    <td>{{ stat.bouncereason }}</td>
                                    <td>{{ stat.datefile }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a href="{% url 'hq:msg-distribution-dlsmsstats' object.pk %}" class="btn btn-primary me-2">Download CSV</a>
                {% else %}
                    <p class="alert alert-info">To get a detailed report about this SMS distribution's outcome, please contact WPSS support with reference: <b>{{ object.short_uid }}</b></p>
                {% endif %}
            {% endif %}
        {% elif object.get_send_date %}
            {% if object.links__count > 0 %}
                {# Loading animation while the messages are sent #}
                {% include "utils/loading_spinner.html" with spinner_progress_info="Message are being sent." %}
            {% else %}
                <div class="alert alert-info">No recipient for this message.{% if object.fallback %} Please check the fallback message.{% endif %}</div>
            {% endif %}
        {% else %}
                {% if object.can_add_fallback %}
                    <a href="{% url 'hq:msg-distribution-fallback-create' object.pk %}" class="btn btn-primary me-2">{% trans "Add fallback message" %}</a>
                {% endif %}
                {% if not object.is_fallback %}
                    <a href="{% url 'hq:msg-distribution-update' object.pk %}" class="btn btn-info me-2">{% trans "Edit the description" %}</a>
                    <a href="{% url 'hq:msg-distribution-send' object.pk %}" class="btn btn-success me-2">{% trans "Send" %}</a>
                {% endif %}
                <a href="{% url 'hq:msg-distribution-delete' object.pk %}" class="btn btn-danger">{% trans "Delete" %}</a>
        {% endif %}
    </section>
{% endblock %}

hq/templates/hq/msgdist/email_stats_by_panel.html
{% load qxsms_tags %}
<div class="table-responsive">
<table class="table table-bordered bg-white">
    <thead class="table-light">
        <tr>
            <th>Panel</th>
            <th>Current Panelists</th>
            {% if schedule %}
                <th title="{{ object.get_send_date }}">Scheduled ({{ days }} days)</th>
            {% else %}
                <th>Attempted</th>
            {% endif %}
            <th>Delivered</th>
             <th title="Delivered messages that have been opened">Opened (at least)</th>
            <th>Soft Bounce</th>
            <th>Hard Bounce</th>
            <th>Other Failures</th>
        </tr>
    </thead>
    <tbody>
    {% for panel, stats in stats.items %}
        {% if panel == "Total" %}
            <tr class="table-success">
                <td>{{ panel }}</td>
                <td>{{ stats.total_panelists }}</td>
                <td>{{ stats.total }}</td>
                <td>{{ stats.success }}</td>
                <td>{{ stats.opened }}</td>
                <td>{{ stats.soft_bounced }}</td>
                <td>{{ stats.hard_bounced }}</td>
                <td>{{ stats.failed }}</td>
            </tr>
        {% else %}
            <tr>
                <td>
                    <a href="{% url 'hq:msg-distribution-history' object.pk stats.pk %}">
                    {{ panel }}
                    </a>
                </td>
                <td>{{ stats.total_panelists }}</td>
                <td>{{ stats.total }}</td>
                <td>{{ stats.success }}</td>
                <td>{{ stats.opened }}</td>
                <td>{{ stats.soft_bounced }}</td>
                <td>{{ stats.hard_bounced }}</td>
                <td>{{ stats.failed }}</td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>
</div>

hq/templates/hq/msgdist/list.html
{% extends 'hq/base.html' %}
{% load static qxsms_tags i18n django_bootstrap5 %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'hq:msg-distribution-list' %}{% trans "Message deliveries" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans "Send individual links to their recipients via email or SMS." %}{% endblock %}
{% block content %}
    <section class="container">
        <p>
            When a link set is generated, every included panelist can
            see their individual link by logging into their account.
        </p>
        <p>
            However, it may be convenient to send an email or a text
            message to eligible panelists, drawing their attention on
            a new survey being available, and directly giving them the
            link they would otherwise find on their portal page.
        </p>
        <p>
            This is exactly the purpose of <b>Message Deliveries</b>.
            For an existing individual link set, the message delivery
            procedure lets you choose a preferred channel (email or
            SMS), a <a href="{% url 'hq:message-list' %}">Qualtrics
            message template</a> to use, a subset of
            panelists to target (eg, those who haven't started the
            survey yet) and schedule a sending date. You can also
            optionaly add a fallback contact mode, that will be used
            to get in touch with panelists not reachable by the
            primary channel.
        </p>
        <p>
            Listed below are message deliveries created so far. Columns
            are to be interpreted as follows:
        <dl>
            <dt>ID</dt>
            <dd>The internal identifier of the message delivery</dd>
            <dt>Created</dt>
            <dd>
                The date when this message delivery was created. By contrast, <b>Send date</b>
                below is the posterior date when the message was sent to panelists.
            </dd>
        </dl>
        </p>
        <a href="{% url 'hq:email-distribution-create' %}" class="btn btn-success mb-3">
            {% icon 'envelope' 'me-2' %}{% trans "New email delivery" %}
        </a>
        <a href="{% url 'hq:sms-distribution-create' %}" class="btn btn-success ms-2 mb-3">
            {% icon 'pen' 'me-2' %}{% trans "New SMS delivery" %}
        </a>
        {% if object_list %}
            <div class="table-responsive">
                <table class="table table-bordered table-hover bg-white">
                    <thead class="table-light">
                    <tr>
                        <th>ID</th>
                        <th>Created</th>
                        <th>Description</th>
                        <th>Link set</th>
                        <th>Type</th>
                        <th>Target</th>
                        <th>Subject</th>
                        <th>Message</th>
                        <th>Send date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for dist in object_list %}
                        <tr>
                            <td><a href="{% url 'hq:msg-distribution-detail' dist.pk %}">{{ dist.short_uid }}</a></td>
                            <td>{{ dist.created_date|date:'Y-m-d H\hi' }}</td>
                            <td>{{dist.description}}</td>
                            <td><a href="{% url 'hq:link-distribution-detail' dist.link_distribution.pk %}">{{ dist.link_distribution.description }}</a></td>
                            <td>{{ dist.get_contact_mode_display }}</td>
                            <td>{{ dist.get_target_display }}</td>
                            <td>{{ dist.subject.description }}</td>
                            <td>{{ dist.message.description }}</td>
                            <td>{{ dist.send_date|date:'Y-m-d H\hi'|default:'Not scheduled' }}</td>
                        </tr>
                        {% if dist.has_fallback %}
                            {% with dist.fallback as f %}
                                <tr>
                                    <td style="border-left: 20px solid #28a745">
                                        {% icon 'reply-fill' 'me-2' 'fallback-row' %}
                                        <a href="{% url 'hq:msg-distribution-detail' f.pk %}">{{ f.short_uid }}</a>
                                    </td>
                                    <td>{{ f.created_date|date:'Y-m-d H\hi' }}</td>
                                    <td>{{f.description}}</td>
                                    <td><a href="{% url 'hq:link-distribution-detail' f.link_distribution.pk %}">{{ f.link_distribution.description }}</a></td>
                                    <td>{{ f.get_contact_mode_display }}</td>
                                    <td>{{ f.get_target_display }}</td>
                                    <td>{{ f.subject.description }}</td>
                                    <td>{{ f.message.description }}</td>
                                    <td class="table-secondary"></td>
                                </tr>
                            {% endwith %}
                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% bootstrap_pagination page=page_obj url=request.get_full_path %}
        {% else %}
            <div class="alert alert-info">{% trans "No message deliveries have been created yet." %}</div>
        {% endif %}
    </section>
{% endblock %}

hq/templates/hq/msgdist/msgdist_details.html
<table class="table table-bordered table-striped">
    <tr>
        <th>UID</th>
        <td><a href="{% url 'hq:msg-distribution-detail' object.pk %}">{{ object.short_uid }}</a></td>
    </tr>
    <tr>
        <th>Type</th><td>{{ object.get_contact_mode_display }}</td>
    </tr>
    <tr>
        <th>Target</th><td>{{ object.get_target_display }}</td>
    </tr>
    <tr>
        <th>Link set</th>
        <td>
            <a href="{% url 'hq:link-distribution-detail' object.link_distribution.pk %}">{{ object.link_distribution.description }}</a>
        </td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description}}</td>
    </tr>
    {% if object.subject %}
        <tr>
            <th>Subject</th>
            <td>{{ object.subject.description }}</td>
        </tr>
    {% endif %}
    <tr>
        <th>Message</th>
        <td>{{ object.message.description }}</td>
    </tr>
    {% if object.get_send_date %}
        <tr>
            <th>Send date</th> <td>{{ object.get_send_date|date:'Y-m-d H\hi' }}</td>
        </tr>
    {% endif %}
    {% if object.has_fallback %}
        <tr>
            <th>Fallback</th>
            <td>
                <a href="{% url 'hq:msg-distribution-detail' object.fallback.pk %}">
                    ({{ object.fallback.short_uid }}) {{ object.fallback.message.description }}
                </a>
            </td>
        </tr>
    {% elif object.is_fallback %}
        <tr>
            <th>Fallback of</th>
            <td>
                <a href="{% url 'hq:msg-distribution-detail' object.fallback_of.pk %}">
                    ({{ object.fallback_of.short_uid }}) {{ object.fallback_of.message.description }}
                </a>
            </td>
        </tr>
    {% endif %}
</table>