hq/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from hq.views import (
    BlankSlotCreate, BlankSlotDelete, BlankSlotImportCsv, BlankSlotList,
    BlankSlotUpdate, BlankSlotValueList, BlankSlotValueUpdate,
    EmailDistributionCreate, Home, HqProfileUpdate, LinkDistributionCreate,
    LinkDistributionDelete, LinkDistributionDetail, LinkDistributionGenerate,
    LinkDistributionList, ManagerCreate, ManagerDelete, ManagerList,
    ManagerUpdate, MessageDistributionDelete, MessageDistributionDetail,
    MessageDistributionFallbackCreate, MessageDistributionHistory,
    MessageDistributionList, MessageDistributionSend,
    MessageDistributionUpdate, MessageList, PanelCreate, PanelDetail,
    PanelList, PanelManagerAssign, PanelManagerUnassign, PanelmemberList,
    PanelUpdate, ProfileExportCSV, SMSDistributionCreate, SurveyList,
    download_sms_stats,
)
from utils.views import blank_slot_export_csv

app_name = 'hq'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('profile/', HqProfileUpdate.as_view(), name='profile-update'),
    path('panelmembers/', PanelmemberList.as_view(), name='panelmember-list'),
    # SURVEYS
    path('surveys/', SurveyList.as_view(), name='survey-list'),
    # PANELS
    path('panels/', PanelList.as_view(), name='panel-list'),
    path('panels/create/', PanelCreate.as_view(), name='panel-create'),
    path('panels/<int:pk>/', PanelDetail.as_view(), name='panel-detail'),
    path('panels/<int:pk>/update/', PanelUpdate.as_view(), name='panel-update'),
    path('panels/<int:pk>/assign/', PanelManagerAssign.as_view(), name='panel-assign'),
    path('panels/<int:pk>/unassign/', PanelManagerUnassign.as_view(), name='panel-unassign'),
    # BLANK SLOTS
    path('blankslot/', BlankSlotList.as_view(), name='blankslot-list'),
    path('blankslot/create', BlankSlotCreate.as_view(), name='blankslot-create'),
    path('blankslot/<int:pk>/update/', BlankSlotUpdate.as_view(), name='blankslot-update'),
    path('blankslot/<int:pk>/delete', BlankSlotDelete.as_view(), name='blankslot-delete'),
    path('panelmembers/<int:pk>/blankslotvalues/', BlankSlotValueList.as_view(), name='blankslotvalue-list'),
    path('panelmembers/<int:pk>/blankslotvalues/update', BlankSlotValueUpdate.as_view(), name='blankslotvalue-update'),
    # MANAGERS
    path('managers/', ManagerList.as_view(), name='manager-list'),
    path('managers/create/', ManagerCreate.as_view(), name='manager-create'),
    path('managers/<int:pk>/update/', ManagerUpdate.as_view(), name='manager-update'),
    path('managers/<int:pk>/delete/', ManagerDelete.as_view(), name='manager-delete'),
    # MESSAGES
    path('messages/', MessageList.as_view(), name='message-list'),
    # EXPORT
    path('panelist/export/', ProfileExportCSV.as_view(), name='panelist-export'),
    path('blankslot/import/', BlankSlotImportCsv.as_view(), name='blank-slot-import'),
    path('blankslot/export/', blank_slot_export_csv, name='blank-slot-export'),
    # LINK DISTRIBUTIONS
    path('links/', LinkDistributionList.as_view(), name='link-distribution-list'),
    path('links/create/', LinkDistributionCreate.as_view(), name='link-distribution-create'),
    path('links/<int:pk>/', LinkDistributionDetail.as_view(), name='link-distribution-detail'),
    path('links/<int:pk>/delete/', LinkDistributionDelete.as_view(), name='link-distribution-delete'),
    path('links/<int:pk>/generate/', LinkDistributionGenerate.as_view(), name="link-distribution-generate"),
    # MESSAGE DISTRIBUTIONS
    path('msgdist/', MessageDistributionList.as_view(), name='msg-distribution-list'),
    path('msgdist/<int:pk>/', MessageDistributionDetail.as_view(), name='msg-distribution-detail'),
    path('msgdist/<int:pk>/smsstatscsv/', download_sms_stats, name='msg-distribution-dlsmsstats'),
    path('msgdist/create/email/', EmailDistributionCreate.as_view(), name='email-distribution-create'),
    path('msgdist/<int:pk>/delete/', MessageDistributionDelete.as_view(), name='msg-distribution-delete'),
    path('msgdist/create/sms/', SMSDistributionCreate.as_view(), name='sms-distribution-create'),
    path('msgdist/<int:pk>/send/', MessageDistributionSend.as_view(), name='msg-distribution-send'),
    path('msgdist/<int:pk>/panels/<int:panel_pk>/history/',
         MessageDistributionHistory.as_view(), name='msg-distribution-history'),
    path("msgdist/<int:pk>/fallback/", MessageDistributionFallbackCreate.as_view(),
         name='msg-distribution-fallback-create'),
    path('msgdist/<int:pk>/update/', MessageDistributionUpdate.as_view(), name='msg-distribution-update'),

]

panelist/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from panelist.views import (
    EmailChangeView, Help, Home, LinkListView, PhoneChangeView, ProfileUpdate,
)

app_name = 'panelist'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('surveys/', LinkListView.as_view(), name='survey-list'),
    path('help/', Help.as_view(), name='help'),
    path('profile/', ProfileUpdate.as_view(), name='profile-update'),
    path('email-change/', EmailChangeView.as_view(), name='email-change'),
    path('phone-change/', PhoneChangeView.as_view(), name='phone-change'),
]

qxsms/urls.py
# -- DJANGO
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

# -- QXSMS
from panelist.views import EmailChangeConfirm, PhoneChangeConfirm
from qxauth.views import (
    GroupLogin, PasswordChange, PasswordReset, PasswordResetConfirm,
)
from qxsms import settings

app_name = 'qxsms'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GroupLogin.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password-change'),
    path('password-change/reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-change/reset/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(),
         name='password-reset-confirm'),
    path('email-change/<str:uidb64>/<str:token>/', EmailChangeConfirm.as_view(),
         name='email-change-confirm'),
    path('phone-change/<str:uidb64>/<str:token>/', PhoneChangeConfirm.as_view(),
         name='phone-change-confirm'),
    path('p/', include('panelist.urls')),
    path('m/', include('manager.urls')),
    path('hq/', include('hq.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('utils/', include('utils.urls')),
]

if settings.DEBUG:
    import debug_toolbar  # isort:skip

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('hijack/', include('hijack.urls', namespace='hijack')),
        path('dist/', include('distributions.urls'))
    ]

distributions/models.py
# -- STDLIB
import logging
import uuid
from typing import Iterable, List, Set, Tuple

# -- DJANGO
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

# -- QXSMS
from panelist.models import Profile


class Survey(models.Model):
    qx_id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Distribution(models.Model):

    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=200)
    qx_id = models.CharField(max_length=20, unique=True, null=True)
    qx_import_id = models.CharField(max_length=20, unique=True, null=True)
    qx_created_date = models.DateTimeField(null=True)

    class Meta:
        abstract = True
        ordering = ['-created_date']

    @property
    def short_uid(self):
        if self.uid is None:
            return ''
        return self.uid.hex[:8]

    def __str__(self):
        descr = self.description or ''
        return f"({self.short_uid}) {descr}"

    def candidates(self, *args, **kwargs):
        raise NotImplementedError

    def contacts_for_import(self):
        raise NotImplementedError

    def save_links(self):
        raise NotImplementedError

    def get_import_kwargs(self):
        """Keyword arguments as expected by `client.import_contacts()`"""
        return {'list_id': self.qx_list_id, 'contacts': self.contacts_for_import()}


def _update_links(links: Iterable['Link'], qx_links: List[dict]) -> Tuple[List['Link'], List['Link']]:
    """Set `Link` attributes using links fetched from Qualtrics

    The normal behavior is that each `Link` instance has exactly one counterpart in `qx_list`.
    If no corresponding Qualtrics link is found, log the error.
    Return updated and skipped instances separately to the caller.
    """
    by_ext_ref = {qxl['externalDataReference']: qxl for qxl in qx_links}
    updated = []
    skipped = []
    for link in links:
        ext_ref = link.profile_id.hex
        try:
            qx_link = by_ext_ref[ext_ref]
        except KeyError:
            logging.error("missing Qualtrics link for %s", link.profile_id)
            skipped.append(link)
            continue
        link.qx_contact_id = qx_link.get('contactId')
        link.url = qx_link.get('link')
        if not (link.qx_contact_id and link.url):
            logging.error("missing contactId or link in record: %s", qx_link)
            skipped.append(link)
            continue
        updated.append(link)
    return updated, skipped


class LinkDistribution(Distribution):

    qx_list_id = models.CharField(max_length=20, unique=True, null=True)
    expiration_date = models.DateTimeField(blank=False, null=True)
    survey = models.ForeignKey('Survey', to_field='qx_id', related_name="distributions",
                               limit_choices_to={'is_active': True}, on_delete=models.PROTECT)
    panels = models.ManyToManyField('hq.Panel', related_name="distributions")

    def get_absolute_url(self):
        return reverse('dist:detail', args=[self.pk])

    def candidates(self):
        return Profile.objects.filter(panel__in=self.panels.all(), is_opt_out=False)

    @property
    def count_candidates(self):
        return self.candidates().count()

    def contacts_for_import(self):
        """Serialize contacts that need a link, in the format expected by Qualtrics imports

        Intended to be called *after* `save_links()`. Another choice would have been to call
        `candidates()` to get the target queryset, but this would leave the possibility of the set
        of candidates having changed since we called `save_links()`...
        """
        profiles = Profile.objects.prefetch_related('blankslotvalue_set__blankslot').filter(link__distribution=self)
        return [p.to_json() for p in profiles]

    def save_links(self):
        """Create links with empty URLs to record the profiles for which link generation is intended

        By creating `Link` instances *before* creating the distribution on Qualtrics, we can confirm that
        all intended recipients indeed got a link generated.
        """
        profiles = self.candidates()
        links = [Link(profile=profile, distribution=self) for profile in profiles]
        self.links.all().delete()
        return Link.objects.bulk_create(links)

    def update_links(self, qx_links: List[dict]) -> Tuple[List['Link'], List['Link']]:
        """Update database links with data from their corresponding Qualtrics link

        `Link` instances for each recipient saved in the database before the Qualtrics distribution is created.
        Once the links are generated on Qualtrics and retrieved, we need to set `Link.qx_contact_id` and
        `Link.url` on their counterparts.

        The pairing between a Qualtrics link and a database `Link` is done using `externalDataReference`, which
        matches `Link.profile_id`.
        """
        updated, skipped = _update_links(self.links.all(), qx_links)
        Link.objects.bulk_update(updated, fields=['qx_contact_id', 'url'])
        return updated, skipped

    @property
    def is_expired(self):
        return timezone.now() > self.expiration_date


class Link(models.Model):
    # TODO Parse and cache URL components for use in __str__
    URL_PATTERN = r'^.*(?P<survey_qx_id>SV_.*)\?Q_CHL=gl&Q_DL=(?P<qx_id>.*)$'

    profile = models.ForeignKey('panelist.Profile', to_field='uid', related_name='links', related_query_name='link',
                                on_delete=models.CASCADE)
    distribution = models.ForeignKey('LinkDistribution', on_delete=models.CASCADE,
                                     related_name='links', related_query_name='link')
    url = models.URLField()
    qx_contact_id = models.CharField(max_length=20)

    class Meta:
        unique_together = ('profile', 'distribution')

    def __str__(self):
        dist_id = profile_id = ""
        if self.distribution_id is not None:
            dist_id = str(self.distribution_id)[:8]
        if self.profile_id is not None:
            profile_id = str(self.profile_id)[:8]
        return (f"dist={dist_id}, "
                f"profile={profile_id}")


# Message distributions (Email and SMS)
# -------------------------------------

class MessageDistribution(Distribution):

    MODE_EMAIL = 0
    MODE_SMS = 1
    CONTACT_MODE_CHOICES = (
        (MODE_EMAIL, _("Email")),
        (MODE_SMS, _("SMS")),
    )

    TARGET_ALL = 0
    TARGET_NOT_FINISHED = 1
    TARGET_FINISHED = 2
    TARGET_CHOICES = (
        (TARGET_ALL, _("All")),
        (TARGET_NOT_FINISHED, _("Not finished (proper target for reminders)")),
        (TARGET_FINISHED, _("Finished"))
    )

    link_distribution = models.ForeignKey('LinkDistribution', on_delete=models.CASCADE,
                                          related_name="%(class)ss", related_query_name="%(class)s",
                                          # TODO Really necessary restriction ?
                                          limit_choices_to={'qx_id__isnull': False})
    qx_batch_id = models.CharField(max_length=20, unique=True, null=True)
    contact_mode = models.PositiveSmallIntegerField(choices=CONTACT_MODE_CHOICES)
    target = models.PositiveSmallIntegerField(choices=TARGET_CHOICES, verbose_name=_("Target recipients"))
    send_date = models.DateTimeField(blank=False, null=True)
    links = models.ManyToManyField('Link', related_name="message_distributions",
                                   related_query_name='message_distribution')
    message = models.ForeignKey('Message', related_name="email_message_of_set",
                                related_query_name='email_message_of', on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey('Message', related_name="email_subject_of_set",
                                related_query_name='email_subject_of', on_delete=models.SET_NULL, null=True)
    fallback_of = models.OneToOneField('self', related_name='fallback', null=True, on_delete=models.CASCADE)

    @property
    def qx_list_id(self):
        list_id = None
        if self.link_distribution_id is not None:
            list_id = self.link_distribution.qx_list_id
        return list_id

    @property
    def is_email(self):
        return self.contact_mode == MessageDistribution.MODE_EMAIL

    @property
    def is_sms(self):
        return self.contact_mode == MessageDistribution.MODE_SMS

    @property
    def fallback_contact_mode(self):
        return MessageDistribution.MODE_EMAIL if self.is_sms else MessageDistribution.MODE_SMS

    @property
    def contact_label(self):
        return "Sms" if self.is_sms else "Email"

    @property
    def fallback_label(self):
        return "Sms" if self.is_email else "Email"

    @property
    def is_fallback(self):
        return self.fallback_of is not None

    @property
    def has_fallback(self):
        return hasattr(self, 'fallback')

    @property
    def can_add_fallback(self):
        return not (self.is_fallback or self.has_fallback)

    @property
    def has_history(self):
        """Whether a detailed history of response statuses is available

        Qualtrics does not seem to support response history for SMS distributions.
        """
        return self.qx_id and self.is_email

    def get_send_date(self):
        if self.fallback_of is not None:
            return self.fallback_of.send_date
        return self.send_date

    def get_absolute_url(self):
        return reverse('dist:msgd:detail', args=[self.pk])

    def contacts_for_import(self):
        return [_contact_from_link(link) for link in self.links.select_related('profile__panel')]

panelist/templates/panelist/base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static qxsms_tags %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/panelist.css' %}?{{ QXSMS_VERSION }}">
{% endblock %}
{% block menu_links %}
    {% if request.user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'panelist:survey-list' %}">{% trans "My surveys" %}</a>
        <a class="nav-item nav-link" href="{% url 'panelist:help' %}">{% trans "Help" %}</a>
    {% endif %}
{% endblock %}
{% block profile_link %}{% url 'panelist:profile-update' %}{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:home' %}{{ INSTANCE_NAME }}{% endbreadcrumbitem %}
{% endblock %}

panelist/templates/panelist/email_change.html
{% extends 'panelist/base.html' %}
{% load i18n qxsms_tags django_bootstrap5 %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:profile-update' %}{% trans "Change your email" %}{% endbreadcrumbitem %}
{% endblock %}

{% block content %}
    <section class="container">
        {% blocktrans trimmed %}
            <p>This page allows you to change the email address linked to your account. We need to ensure that the new address is valid as it is used as a login identifier and as a primary means of communication,</p>
            <p>Once you have changed the email address, you will receive a link to validate the new email address. The change will be effective only after the link is clicked. In the meantime, your old email address will still be used for login and communication.</p>
        {% endblocktrans %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success me-2">{% trans "Send request" %}</button>
            {% url 'panelist:profile-update' as cancel_url %}
            {% include 'utils/cancel_button.html' %}
        </form>
    </section>
{% endblock %}

panelist/templates/panelist/email_change_confirm.html
{% extends 'panelist/base.html' %}
{% load qxsms_tags %}
{% load i18n %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:profile-update' %}{% trans "Confirm your email" %}{% endbreadcrumbitem %}
{% endblock %}
{% block content %}
    <section class="container">
        {% if validlink %}
            {% blocktrans with email=user.email  temp_email=user.profile.temp_email trimmed %}
                <p>Are you sure you want to change your email {{ email }} by {{ temp_email }}?</p>
            {% endblocktrans %}
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success me-2">{% trans "Confirm request" %}</button>
            </form>
        {% else %}
            <p>{% trans "This link is invalid, possibly because it has already been used. Please request a new link to change your email." %}</p>
        {% endif %}
    </section>
{% endblock %}

panelist/templates/panelist/email_change_email.html
{% load i18n %}
{% blocktrans %}
We have sent you this email because you requested to change the email address linked to your account on {{ site_name }}.
Please visit the link below to confirm the new email address:
{% endblocktrans %}
{{ protocol }}://{{ domain }}{% url 'email-change-confirm' uidb64=uid token=token %}

panelist/templates/panelist/help.html
{% extends 'panelist/base.html' %}
{% load i18n qxsms_tags %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:help' %}{% trans "Help" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% endblock %}
{% block content %}
    {% include "panelist/help_text.html" %}
{% endblock %}

panelist/templates/panelist/help_text.html
{% load static i18n %}
<section class="container">
    <article class="mt-5">
        {% blocktrans trimmed %}
            <p><b>The {{ INSTANCE_NAME }}</b> is a study of carefully selected people who are asked to give their views on a wide range of topical social issues, such as family life, work, health, the media and politics. The information collected will provide researchers and policy makers (amongst others) with valuable insights regarding the most important topics in our society today.</p>
            <p>A new survey will be issued every 1-2 months and you will receive a ‘thank you’ gift of <b>{{ incentive_amount }}</b> with each survey invitation.</p>
            <p>Only you can complete the survey so please do not share your details with anyone else.</p>
            <p>No special knowledge is needed to answer the surveys  there are no wrong answers, we just want to know your opinions and experiences.</p>
            <p>Your data will be handled in the strictest confidence and in accordance with the General Data Protection Regulation (GDPR).</p>
        {% endblocktrans %}
        <h1>{% trans "Contact us" %}</h1>
        {% if contact_info %}
            <p>{{ contact_info }}</p>
        {% else %}
            {% blocktrans trimmed with first_name=manager.first_name last_name=manager.last_name email=manager.email phone=manager.phone %}
                <p>If you need to get in touch, please contact <b>{{ first_name }} {{ last_name }} (<a href="mailto:{{ email }}">{{ email }}</a> / <a href="tel:{{ phone }}">{{ phone }}</a>)</b>.</p>
            {% endblocktrans %}
        {% endif %}
    </article>
</section>

panelist/templates/panelist/index.html
{% extends 'panelist/base.html' %}
{% load i18n %}
{% block breadcrumb %}
    {{ block.super }}
{% endblock %}
{% block title_lead %}{% blocktrans %}Welcome {{ panelist_first_name }}{% endblocktrans %}{% endblock %}
{% block content %}
    <section class="container">
        <article>
            <h1>{% trans "Latest surveys" %}</h1>
            {% include 'panelist/utils/survey_list.html' %}
            {% if page_obj.has_next %}
                <a class="btn btn-secondary mt-3" href="{% url 'panelist:survey-list' %}">{% trans "See more" %}</a>
            {% endif %}
        </article>
        <article class="mt-5">
            <h1>{% trans "Other actions" %}</h1>
            <div class="row">
                <div class="col-lg-4">
                    <a class="card text-center mb-3" href="{% url 'panelist:profile-update' %}">
                        <div class="card-body">
                            <span class="card-title mb-0">{% trans "Change your contact details" %}</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4">
                    <a class="card text-center" href="{% url 'panelist:help' %}">
                        <div class="card-body">
                            <span class="card-title mb-0">{% trans "Help" %}</span>
                        </div>
                    </a>
                </div>
            </div>
        </article>
    </section>
{% endblock %}

panelist/templates/panelist/password_change.html
{% extends 'panelist/base.html' %}
{% load qxsms_tags django_bootstrap5 i18n %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem %}{%trans "Password change" %}{% endbreadcrumbitem %}
{% endblock %}

{% block title_lead %}{{ user }}{% endblock %}

{% block content %}
    {% url 'panelist:profile-update' as cancel_url %}
    {% include 'password_change_form.html' %}
{% endblock %}

panelist/templates/panelist/phone_change.html
{% extends 'panelist/base.html' %}
{% load i18n qxsms_tags django_bootstrap5 %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:profile-update' %}{% trans "Change your phone number" %}{% endbreadcrumbitem %}
{% endblock %}

{% block content %}
    <section class="container">
        {% blocktrans trimmed %}
            <p>This page allows you to change the phone number linked to your account. We need to ensure that the new number is valid as it is used as a login identifier and as a primary means of communication,</p>
            <p>Once you have changed the phone number, you will receive a text message with a link to validate the new number. The change will be effective only after the link is visited. In the meantime, your old phone number will still be used for login and communication.</p>
        {% endblocktrans %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success me-2">{% trans "Send request" %}</button>
            {% url 'panelist:profile-update' as cancel_url %}
            {% include 'utils/cancel_button.html' %}
        </form>
    </section>
{% endblock %}

panelist/templates/panelist/phone_change_confirm.html
{% extends 'panelist/base.html' %}
{% load qxsms_tags %}
{% load i18n %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:profile-update' %}{% trans "Confirm your phone number" %}{% endbreadcrumbitem %}
{% endblock %}
{% block content %}
    <section class="container">
        {% if validlink %}
            {% blocktrans with phone=user.phone new_phone=user.profile.temp_phone %}
                <p>Are you sure you want to change your phone number {{ phone }} by {{ new_phone }}?</p>
            {% endblocktrans %}
            <br>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success me-2">{% trans "Confirm request" %}</button>
            </form>
        {% else %}
            <p>{% trans "This link is invalid, possibly because it has already been used. Please request a new link to change your phone number." %}</p>
        {% endif %}
    </section>
{% endblock %}

panelist/templates/panelist/phone_change_sms.html
{% load i18n %}
{% blocktrans %}
We have sent you this text message because you requested to change the phone number linked to your account on {{ site_name }}.
Please visit the link below to confirm the new phone number:
{% endblocktrans %}
{{ protocol }}://{{ domain }}{% url 'phone-change-confirm' uidb64=uid token=token %}

panelist/templates/panelist/profile_update.html
{% extends 'panelist/base.html' %}
{% load i18n qxsms_tags django_bootstrap5 %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:profile-update' %}{% trans "Profile" %}{% endbreadcrumbitem %}
{% endblock %}

{% block title_lead %}{% trans "Change your contact details" %}{% endblock %}

{% block content %}
    <section class="container">
        <form method="post">
            <div class="mb-3">
                <label for="id_panelist_id" class="form-label">Panelist ID</label>
                <input id="id_panelist_id" class="form-control" type="text" value="{{ object.panelist_id }}" disabled/>
            </div>
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success me-2">{% trans "Save" %}</button>
            <a href="{% url 'password-change' %}" class="btn btn-secondary me-2">{% trans "Change your password" %}</a>
            <a href="{% url 'panelist:email-change' %}" class="btn btn-secondary me-2">{% trans "Change your email" %}</a>
            <a href="{% url 'panelist:phone-change' %}" class="btn btn-secondary me-2">{% trans "Change your phone number" %}</a>
            {% url 'panelist:home' as cancel_url %}
            {% include 'utils/cancel_button.html' %}
        </form>
    </section>
{% endblock %}

panelist/templates/panelist/survey_list.html
{% extends 'panelist/base.html' %}
{% load i18n qxsms_tags %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'panelist:survey-list' %}{% trans "My surveys" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% endblock %}
{% block content %}
    <section class="container">
        {% include 'panelist/utils/survey_list.html' %}
    </section>
{% endblock %}