hq/urls.py
# -- DJANGO
from django.urls import path

# -- QXSMS
from hq.views import (
    BlankSlotCreate, BlankSlotDelete, BlankSlotImportCsv, BlankSlotList,
    BlankSlotUpdate, BlankSlotValueList, BlankSlotValueUpdate,
    EmailDistributionCreate, Home, HqProfileUpdate, LinkDistributionCreate,
    LinkDistributionDelete, LinkDistributionDetail, LinkDistributionGenerate,
    LinkDistributionList, ManagerCreate, ManagerDelete, ManagerList,
    ManagerUpdate, MessageDistributionDelete, MessageDistributionDetail,
    MessageDistributionFallbackCreate, MessageDistributionHistory,
    MessageDistributionList, MessageDistributionSend,
    MessageDistributionUpdate, MessageList, PanelCreate, PanelDetail,
    PanelList, PanelManagerAssign, PanelManagerUnassign, PanelmemberList,
    PanelUpdate, ProfileExportCSV, SMSDistributionCreate, SurveyList,
    download_sms_stats,
)
from utils.views import blank_slot_export_csv

app_name = 'hq'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('profile/', HqProfileUpdate.as_view(), name='profile-update'),
    path('panelmembers/', PanelmemberList.as_view(), name='panelmember-list'),
    # SURVEYS
    path('surveys/', SurveyList.as_view(), name='survey-list'),
    # PANELS
    path('panels/', PanelList.as_view(), name='panel-list'),
    path('panels/create/', PanelCreate.as_view(), name='panel-create'),
    path('panels/<int:pk>/', PanelDetail.as_view(), name='panel-detail'),
    path('panels/<int:pk>/update/', PanelUpdate.as_view(), name='panel-update'),
    path('panels/<int:pk>/assign/', PanelManagerAssign.as_view(), name='panel-assign'),
    path('panels/<int:pk>/unassign/', PanelManagerUnassign.as_view(), name='panel-unassign'),
    # BLANK SLOTS
    path('blankslot/', BlankSlotList.as_view(), name='blankslot-list'),
    path('blankslot/create', BlankSlotCreate.as_view(), name='blankslot-create'),
    path('blankslot/<int:pk>/update/', BlankSlotUpdate.as_view(), name='blankslot-update'),
    path('blankslot/<int:pk>/delete', BlankSlotDelete.as_view(), name='blankslot-delete'),
    path('panelmembers/<int:pk>/blankslotvalues/', BlankSlotValueList.as_view(), name='blankslotvalue-list'),
    path('panelmembers/<int:pk>/blankslotvalues/update', BlankSlotValueUpdate.as_view(), name='blankslotvalue-update'),
    # MANAGERS
    path('managers/', ManagerList.as_view(), name='manager-list'),
    path('managers/create/', ManagerCreate.as_view(), name='manager-create'),
    path('managers/<int:pk>/update/', ManagerUpdate.as_view(), name='manager-update'),
    path('managers/<int:pk>/delete/', ManagerDelete.as_view(), name='manager-delete'),
    # MESSAGES
    path('messages/', MessageList.as_view(), name='message-list'),
    # EXPORT
    path('panelist/export/', ProfileExportCSV.as_view(), name='panelist-export'),
    path('blankslot/import/', BlankSlotImportCsv.as_view(), name='blank-slot-import'),
    path('blankslot/export/', blank_slot_export_csv, name='blank-slot-export'),
    # LINK DISTRIBUTIONS
    path('links/', LinkDistributionList.as_view(), name='link-distribution-list'),
    path('links/create/', LinkDistributionCreate.as_view(), name='link-distribution-create'),
    path('links/<int:pk>/', LinkDistributionDetail.as_view(), name='link-distribution-detail'),
    path('links/<int:pk>/delete/', LinkDistributionDelete.as_view(), name='link-distribution-delete'),
    path('links/<int:pk>/generate/', LinkDistributionGenerate.as_view(), name="link-distribution-generate"),
    # MESSAGE DISTRIBUTIONS
    path('msgdist/', MessageDistributionList.as_view(), name='msg-distribution-list'),
    path('msgdist/<int:pk>/', MessageDistributionDetail.as_view(), name='msg-distribution-detail'),
    path('msgdist/<int:pk>/smsstatscsv/', download_sms_stats, name='msg-distribution-dlsmsstats'),
    path('msgdist/create/email/', EmailDistributionCreate.as_view(), name='email-distribution-create'),
    path('msgdist/<int:pk>/delete/', MessageDistributionDelete.as_view(), name='msg-distribution-delete'),
    path('msgdist/create/sms/', SMSDistributionCreate.as_view(), name='sms-distribution-create'),
    path('msgdist/<int:pk>/send/', MessageDistributionSend.as_view(), name='msg-distribution-send'),
    path('msgdist/<int:pk>/panels/<int:panel_pk>/history/',
         MessageDistributionHistory.as_view(), name='msg-distribution-history'),
    path("msgdist/<int:pk>/fallback/", MessageDistributionFallbackCreate.as_view(),
         name='msg-distribution-fallback-create'),
    path('msgdist/<int:pk>/update/', MessageDistributionUpdate.as_view(), name='msg-distribution-update'),

]

qxsms/urls.py
# -- DJANGO
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

# -- QXSMS
from panelist.views import EmailChangeConfirm, PhoneChangeConfirm
from qxauth.views import (
    GroupLogin, PasswordChange, PasswordReset, PasswordResetConfirm,
)
from qxsms import settings

app_name = 'qxsms'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', GroupLogin.as_view(), name='login'),
    path('password-change/', PasswordChange.as_view(), name='password-change'),
    path('password-change/reset/', PasswordReset.as_view(), name='password-reset'),
    path('password-change/reset/<str:uidb64>/<str:token>/', PasswordResetConfirm.as_view(),
         name='password-reset-confirm'),
    path('email-change/<str:uidb64>/<str:token>/', EmailChangeConfirm.as_view(),
         name='email-change-confirm'),
    path('phone-change/<str:uidb64>/<str:token>/', PhoneChangeConfirm.as_view(),
         name='phone-change-confirm'),
    path('p/', include('panelist.urls')),
    path('m/', include('manager.urls')),
    path('hq/', include('hq.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('utils/', include('utils.urls')),
]

if settings.DEBUG:
    import debug_toolbar  # isort:skip

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
        path('hijack/', include('hijack.urls', namespace='hijack')),
        path('dist/', include('distributions.urls'))
    ]

hq/models.py
# -- STDLIB
import logging

# -- DJANGO
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

logger = logging.getLogger(__name__)
User = get_user_model()


class Panel(models.Model):
    managers = models.ManyToManyField(User, blank=True)
    name = models.CharField(max_length=256)
    incentive_amount = models.CharField(max_length=256, blank=True, help_text=_("Value and currency."))
    contact_info = models.TextField(
        null=True,
        blank=True,
        help_text=_("Content that will be displayed in the \"Contact us\" section "
                    "at the end of the panelist portal help page. "
                    "If not set, the manager contact information will be displayed by default.")
    )

    def __str__(self):
        return self.name


class SMSStats(models.Model):
    panelist = models.ForeignKey("panelist.Profile", on_delete=models.CASCADE)
    msgdist = models.ForeignKey("distributions.MessageDistribution", on_delete=models.CASCADE)
    smsstatus = models.CharField(max_length=255, null=True)
    bouncereason = models.CharField(max_length=255, null=True)
    datefile = models.DateTimeField(null=True)

    def __repr__(self):
        return f"{self.panelist}|{self.msgdist}|{self.datefile}"

hq/views.py
# -- STDLIB
import csv
import logging
from datetime import datetime, timezone

# -- DJANGO
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import (
    HttpResponse, HttpResponseNotAllowed, HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, TemplateView
from django.views.generic.base import View
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import (
    BaseFormView, CreateView, DeleteView, FormView, UpdateView,
)

# -- THIRDPARTY
from django_filters.views import FilterView

# -- QXSMS
from distributions import models as distmodels, services, views as distviews
from hq.forms import (
    ManagerAddMultipleForm, ManagerCreateForm, ManagerUpdateForm,
    PanelCreateForm, PanelUpdateForm,
)
from hq.models import Panel, SMSStats
from manager.filters import MessageDeliveryReportFilter
from manager.forms import BlankSlotImportForm
from panelist.models import BlankSlot, Profile
from qxauth.forms import UserUpdateForm
from qxsms import settings
from utils.csvimport import BlankSlotValueResource, ProfileHQResource
from utils.utils import get_panelist_counts
from utils.views import (
    BaseBlankSlotValueList, BaseBlankSlotValueUpdate, csv_response,
)

# -- QXSMS (LOCAL)
from .filters import PanelistsHqFilter

User = get_user_model()

logger = logging.getLogger(__name__)
if settings.DEBUG:
    logger = logging.getLogger('django.server')


class AddRelatedView(SingleObjectMixin, BaseFormView):
    """ Generic view to add a related entity to a model.

    form_class must be a subclass of AddRelatedForm.
    """
    success_view_name = None
    form_class = None
    object = None

    def get(self, request, *args, **kwargs):
        return HttpResponseNotAllowed(permitted_methods=('POST',))

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['owner'] = self.object
        return kwargs

    def get_success_url(self):
        return reverse(self.success_view_name, args=(self.object.pk,))

    def form_invalid(self, form):
        return HttpResponseRedirect(self.get_success_url())

    def form_valid(self, form):
        owner_attr = form.owner_attr
        related = form.cleaned_data[owner_attr]
        getattr(self.object, owner_attr).add(*related)
        return HttpResponseRedirect(self.get_success_url())


class Home(TemplateView):
    template_name = 'hq/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'panelist_count': Profile.objects.count(),
            'panel_count': Panel.objects.count(),
            'manager_count': User.objects.filter(groups__name=settings.QXSMS_GROUP_MANAGERS).count(),
        })
        return context


# Hq
class HqProfileUpdate(SuccessMessageMixin, UpdateView):
    template_name = 'hq/profile_update.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('hq:home')
    success_message = _("Your personal information has been updated")

    def get_object(self, **kwargs):
        return self.request.user


# Managers
class ManagerList(ListView):
    queryset = User.objects.filter(groups__name=settings.QXSMS_GROUP_MANAGERS).annotate(panel_count=Count('panel'))
    template_name = 'hq/manager_list.html'


class ManagerCreate(SuccessMessageMixin, CreateView):
    form_class = ManagerCreateForm
    template_name = 'hq/manager_create.html'
    success_url = reverse_lazy('hq:manager-list')
    success_message = _("Created national coordinator account %(email)s")

    def form_valid(self, form):
        response = super().form_valid(form)
        form.instance.send_welcome(request=self.request)
        return response


class ManagerUpdate(SuccessMessageMixin, UpdateView):
    form_class = ManagerUpdateForm
    template_name = 'hq/manager_update.html'
    success_url = reverse_lazy('hq:manager-list')
    success_message = _("Updated national coordinator account %(email)s")

    def get_queryset(self):
        return User.objects.filter(groups__name=settings.QXSMS_GROUP_MANAGERS)


class ManagerDelete(DeleteView):
    template_name = 'hq/manager_confirm_delete.html'
    success_url = reverse_lazy('hq:manager-list')

    def get_queryset(self):
        return User.objects.filter(groups__name=settings.QXSMS_GROUP_MANAGERS)

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(self.request, _(
            "Deleted national coordinator account %s"
        ) % self.object.email)
        return response


# Distributions
###############
class LinkDistributionList(distviews.LinkDistributionList):
    template_name = 'hq/dist/list.html'


class LinkDistributionCreate(distviews.LinkDistributionCreate):
    template_name = "hq/dist/create.html"
    success_url = reverse_lazy('hq:link-distribution-list')


class LinkDistributionDetail(distviews.LinkDistributionDetail):
    template_name = "hq/dist/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.qx_id:
            skip_cache = 'nocache' in self.request.GET
            history = services.get_distribution_history(qx_id=self.object.qx_id, skip_cache=skip_cache)
            links = self.object.links.exclude(url='')
            history_links = services.merge_links_and_history(links, history)
            stats = services.history_links_stats(history_links)

            # Total check
            for p in stats:
                if stats[p]["not_started"] + stats[p]["started"] + stats[p]["finished"] + stats[p]["failed"]\
                        + stats[p]["partially_finished"] != stats[p]["total"]:
                    error_message = f"panel '{p}' : {stats[p]['not_started']} + {stats[p]['started']} + " \
                                    f"{stats[p]['finished']} + {stats[p]['failed']} + " \
                                    f"{stats[p]['partially_finished']} != {stats[p]['total']}"
                    logger.error(error_message)

            context['records_stats'] = stats
        return context


class LinkDistributionDelete(distviews.LinkDistributionDelete):
    template_name = "hq/dist/delete.html"
    success_url = reverse_lazy('hq:link-distribution-list')
    success_message = _("Deleted set of individual links")


class LinkDistributionGenerate(distviews.LinkDistributionGenerate):
    template_name = "hq/dist/generate.html"

    def get_success_url(self):
        return reverse('hq:link-distribution-detail', args=[self.object.pk])


class MessageDistributionList(distviews.MessageDistributionList):
    template_name = "hq/msgdist/list.html"
    paginate_by = 25


def download_sms_stats(request, pk):
    filename = f"stats_sms_{distmodels.MessageDistribution.objects.get(pk=pk).short_uid}.csv"
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'

    writer = csv.DictWriter(response, fieldnames=["Panelist ID", "Panel", "Status", "Bounce Reason",
                                                  "Last status update"])

    writer.writeheader()
    for stat in SMSStats.objects.filter(msgdist_id=pk):
        writer.writerow({"Panelist ID": stat.panelist.panelist_id, "Panel": stat.panelist.panel.name,
                         "Status": stat.smsstatus, "Bounce Reason": stat.bouncereason,
                         "Last status update": stat.datefile})

    return response


class MessageDistributionDetail(DetailView):
    template_name = "hq/msgdist/detail.html"
    queryset = distmodels.MessageDistribution.objects.annotate(Count('links'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.qx_id is None:
            return context
        skip_cache = 'nocache' in self.request.GET

        # Include global stats if we have an SMS
        if self.object.is_sms:
            statssms = SMSStats.objects.filter(msgdist=self.object)
            context['detailedstatssms'] = statssms
            stats = services.get_distribution_stats(qx_id=self.object.qx_id,
                                                    survey_id=settings.QXSMS_SEND_SURVEY,
                                                    skip_cache=skip_cache,
                                                    is_sms=True)
        # For emails, include stats aggregated by panel
        else:
            history = services.get_distribution_history(qx_id=self.object.qx_id, skip_cache=skip_cache)
            links = self.object.links.select_related('profile__panel')
            links_with_history = services.merge_links_and_history(links, history)
            stats = services.msg_distributions_stats(links_with_history)

        context['schedule'] = False
        if datetime.now(timezone.utc) < self.object.get_send_date():
            context['schedule'] = True
            context['days'] = (self.object.get_send_date() - datetime.now(timezone.utc)).days

        context['stats'] = stats
        return context


class MessageDistributionDelete(distviews.MessageDistributionDelete):
    template_name = "hq/msgdist/delete.html"
    success_message = _("Deleted message distribution")

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response

    def get_success_url(self):

hq/templates/hq/blankslot_confirm_delete.html
{% extends 'hq/blankslot_list.html' %}
{% load qxsms_tags i18n %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem %}{{ blankslot.name }}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans 'Please confirm' %}{% endblock %}
{% block content %}
    <section class="container">
        <div class="d-flex justify-content-center">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title">
                        {% blocktrans with name=blankslot.name %}
                            You are about to permanently delete the variable <strong>{{ name }}</strong>.
                            Proceed ?
                        {% endblocktrans %}
                    </h1>
                    <form action="{% url 'hq:blankslot-delete' blankslot.pk %}" method="post" class="text-center">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger me-2">{% trans 'Yes' %}</button>
                        {% url 'hq:blankslot-update' blankslot.pk as cancel_url %}
                        {% include 'utils/cancel_button.html' %}
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

hq/templates/hq/blankslot_update.html
{% extends 'hq/blankslot_list.html' %}
{% load qxsms_tags django_bootstrap5 i18n %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem %}{{ blankslot.name }}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans 'Additional variable edition' %}{% endblock %}
{% block content %}
    <section class="container">
        <form method="post" action="{% url 'hq:blankslot-update' object.pk %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success me-2">{% trans 'Save' %}</button>
            {% url 'hq:blankslot-list' as cancel_url %}
            {% include 'utils/cancel_button.html' %}
            <a href="{% url 'hq:blankslot-delete' blankslot.pk %}" class="float-end ms-2 btn btn-danger">{% trans 'Delete' %}</a>
        </form>
    </section>
{% endblock %}

hq/templates/hq/panel_create.html
{% extends 'hq/panel_list.html' %}
{% load qxsms_tags django_bootstrap5 i18n %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'hq:panel-create' %}{% trans "New panel" %}{% endbreadcrumbitem %}
{% endblock %}

{% block title_lead %}{% trans "Choose a name and assign national coordinators" %}{% endblock %}

{% block content %}
    <section class="container">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-success me-2">{% trans "Create" %}</button>
            {% url 'hq:panel-list' as cancel_url %}
            {% include 'utils/cancel_button.html' %}
        </form>
    </section>
{% endblock %}

hq/templates/hq/panel_member_list.html
{% extends 'hq/base.html' %}
{% load qxsms_tags i18n django_bootstrap5 %}
{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem 'hq:panelmember-list' %}{% trans "Panelists" %}{% endbreadcrumbitem %}
{% endblock %}
{% block title_lead %}{% trans "All panelist accounts currently managed by the application" %}{% endblock %}
{% block content %}
    <section class="container mw-1920">
        <div class="btn-toolbar mb-3">
            <div class="btn-group me-2">
                <div class="btn-group">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="import-menu-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        {% icon 'upload' 'me-2' %}{% trans "Import" %}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="import-menu-dropdown">
                        <a class="dropdown-item" href="{% url 'hq:blank-slot-import' %}">{% trans "Additional variables" %}</a>
                    </div>
                </div>
                <div class="btn-group">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="export-menu-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        {% icon 'download' 'me-2' %}{% trans "Export" %}
                    </button>
                    <div class="dropdown-menu" aria-labelledby="export-menu-dropdown">
                        <a class="dropdown-item" href="{% url 'hq:panelist-export' %}">{% trans "Panelists" %}</a>
                        <a class="dropdown-item" href="{% url 'hq:blank-slot-export' %}">{% trans "Additional variables" %}</a>
                    </div>
                </div>
            </div>
            <a class="btn btn-info ms-auto" href="{% url 'hq:blankslot-list' %}">{% trans "Manage additional variables" %}</a>
        </div>
        <p>
            Summary of language codes: {% for lang in language_codes %}'{{ lang }}'{% if not forloop.last %} {% endif %}{% endfor %}
        </p>
        {% include 'utils/table_filter.html' with form=filter.form counts=counts %}
        {% if object_list %}
            <div class="table-responsive">
                <table class="table table-bordered table-hover bg-white">
                    <thead class="table-light">
                        <tr>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    ID{% include 'utils/table_header_column_sort.html' with order_by='ess_id' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Age{% include 'utils/table_header_column_sort.html' with order_by='year_of_birth' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Sex{% include 'utils/table_header_column_sort.html' with order_by='sex' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Language{% include 'utils/table_header_column_sort.html' with order_by='language' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Email{% include 'utils/table_header_column_sort.html' with order_by='email' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Phone{% include 'utils/table_header_column_sort.html' with order_by='phone' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Address{% include 'utils/table_header_column_sort.html' with order_by='address' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Internet use{% include 'utils/table_header_column_sort.html' with order_by='internet_use' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Opt out{% include 'utils/table_header_column_sort.html' with order_by='is_opt_out' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Opt out date{% include 'utils/table_header_column_sort.html' with order_by='opt_out_date' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Opt out reason{% include 'utils/table_header_column_sort.html' with order_by='opt_out_reason' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Delete contact data{% include 'utils/table_header_column_sort.html' with order_by='delete_contact_data' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Delete survey data{% include 'utils/table_header_column_sort.html' with order_by='delete_survey_data' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    Out of country{% include 'utils/table_header_column_sort.html' with order_by='out_of_country' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    No incentive{% include 'utils/table_header_column_sort.html' with order_by='no_incentive' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    No letter{% include 'utils/table_header_column_sort.html' with order_by='no_letter' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    No text{% include 'utils/table_header_column_sort.html' with order_by='no_text' %}
                                </div>
                            </th>
                            <th>
                                <div class="d-flex justify-content-between align-items-end">
                                    No email{% include 'utils/table_header_column_sort.html' with order_by='no_email' %}
                                </div>
                            </th>
                            <th>Additional variables</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for panelist in object_list %}
                        <tr>
                            <td>{{ panelist.panelist_id }}</td>
                            <td>{{ panelist.age }}</td>
                            <td>{{ panelist.get_sex_display }}</td>
                            <td><span class="badge rounded-pill bg-secondary">{{ panelist.language|upper }}</span></td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.email %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.phone %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.address %}</td>
                            <td>{{ panelist.get_internet_use_display }}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.is_opt_out %}</td>
                            <td>{{ panelist.opt_out_date }}</td>
                            <td>{{ panelist.opt_out_reason }}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.delete_contact_data %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.delete_survey_data %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.out_of_country %}</td>
                            <th>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.no_incentive %}</th>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.no_letter %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.no_text %}</td>
                            <td>{% include "hq/utils/member_list_boolean.html" with panelist_attribute=panelist.no_email %}</td>
                            <td>
                                <a class="btn btn-sm btn-info" href="{% url 'hq:blankslotvalue-list' panelist.pk %}">
                                    {% icon 'search' %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% bootstrap_pagination page=page_obj url=request.get_full_path %}
        {% else %}
            <div class="alert alert-info">{% trans "No panelist" %}</div>
        {% endif %}
    </section>
{% endblock %}

hq/templates/hq/password_change.html
{% extends 'hq/base.html' %}
{% load qxsms_tags django_bootstrap5 i18n %}

{% block breadcrumb %}
    {{ block.super }}
    {% breadcrumbitem %}{% trans "Password change" %}{% endbreadcrumbitem %}
{% endblock %}

{% block title_lead %}{{ user }}{% endblock %}

{% block content %}
    {% url 'hq:profile-update' as cancel_url %}
    {% include 'password_change_form.html' %}
{% endblock %}